<?php
// modules/Shared/Domain/Enum/ErrorCodeEnum.php
declare(strict_types=1);

namespace Modules\Shared\Domain\Enum;

enum ErrorCodeEnum: string
{
    case NOT_FOUND = 'NOT_FOUND';
    case VALIDATION_FAILED = 'VALIDATION_FAILED';
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case FORBIDDEN = 'FORBIDDEN';
    case INTERNAL_ERROR = 'INTERNAL_ERROR';
    case USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
    case USER_NOT_ACTIVE = 'USER_NOT_ACTIVE';
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case BANK_ALREADY_EXISTS = 'BANK_ALREADY_EXISTS';
    case FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';
    case TOKEN_EXPIRED = 'TOKEN_EXPIRED';
    case TOKEN_INVALID = 'TOKEN_INVALID';
    case USER_NOT_VERIFIED = 'USER_NOT_VERIFIED';
    case USER_NOT_APPROVED = 'USER_NOT_APPROVED';
    case USER_PENDING = 'USER_PENDING';
    case DUPLICATE_JOIN_REQUEST = 'DUPLICATE_JOIN_REQUEST';
    case JOIN_REQUEST_ALREADY_REVIEWED = 'JOIN_REQUEST_ALREADY_REVIEWED';
    case JOIN_REQUEST_NOT_FOUND = 'JOIN_REQUEST_NOT_FOUND';
    case SHIFT_NOT_FOUND = 'SHIFT_NOT_FOUND';
    case SHIFT_TIME_OVERLAP = 'SHIFT_TIME_OVERLAP';
    case POSITION_MISMATCH = 'POSITION_MISMATCH';
    case SHIFT_ASSIGNMENT_NOT_FOUND = 'SHIFT_ASSIGNMENT_NOT_FOUND';
    case SHIFT_FULL = 'SHIFT_FULL';
    case SHIFT_CONFLICT = 'SHIFT_CONFLICT';
    case GEO_INFEASIBLE = 'GEO_INFEASIBLE';
    case SHIFT_CAPACITY_EXCEEDED = 'SHIFT_CAPACITY_EXCEEDED';
    case INVALID_SHIFT_POSITION = 'INVALID_SHIFT_POSITION';
    case DUPLICATE_SHIFT_ASSIGNMENT = 'DUPLICATE_SHIFT_ASSIGNMENT';

    public function getHttpStatus(): int
    {
        return match ($this) {
            self::NOT_FOUND, self::JOIN_REQUEST_NOT_FOUND, self::SHIFT_NOT_FOUND, self::SHIFT_ASSIGNMENT_NOT_FOUND => 404,
            self::VALIDATION_FAILED, self::JOIN_REQUEST_ALREADY_REVIEWED, self::SHIFT_TIME_OVERLAP, self::POSITION_MISMATCH, self::SHIFT_FULL, self::SHIFT_CONFLICT, self::GEO_INFEASIBLE, self::SHIFT_CAPACITY_EXCEEDED, self::INVALID_SHIFT_POSITION => 422,
            self::UNAUTHORIZED, self::TOKEN_EXPIRED, self::TOKEN_INVALID, self::INVALID_CREDENTIALS => 401,
            self::FORBIDDEN, self::USER_NOT_ACTIVE, self::USER_NOT_VERIFIED, self::USER_NOT_APPROVED, self::USER_PENDING => 403,
            self::INTERNAL_ERROR, self::FILE_UPLOAD_FAILED => 500,
            self::USER_ALREADY_EXISTS, self::BANK_ALREADY_EXISTS, self::DUPLICATE_JOIN_REQUEST, self::DUPLICATE_SHIFT_ASSIGNMENT => 409,
        };
    }
}
