sonar.projectKey=events_app
sonar.projectName=events_app

sonar.host.url=http://localhost:9000
sonar.login=sqp_f51641db3b5299da79f345b969d650e141d62231

sonar.sources=.
sonar.exclusions=vendor/**,storage/**,bootstrap/**,node_modules/**,public/**
